apiVersion: cloud.aruba.it/v1alpha1
kind: ArubaCloudServer
metadata:
  name: aruba-resource-v45
  namespace: default
spec:
  tenant: ARU-329997
  tags:
    - sample-tag
  location:
    value: ITBG-Bergamo
  dataCenter: ITBG-1
  vpcReference:
    name: aruba-resource-v45
    namespace: default
  vpcPreset: False
  flavorName: CSO4A8
  subnetReferences:
    - name: aruba-resource-v45
      namespace: default
  elasticIpReference:
    name: aruba-resource-v45
    namespace: default
  securityGroupReferences:
    - name: aruba-resource-v45
      namespace: default
  keyPairReference:
    name: aruba-resource-v45
    namespace: default
  bootVolumeReference:
    name: aruba-resource-v45
    namespace: default
  dataVolumeReferences:
    - name: aruba-resource-v45-data
      namespace: default
  projectReference:
    name: aruba-resource-v45
    namespace: default
