apiVersion: cloud.aruba.it/v1alpha1
kind: ArubaVpc
metadata:
  name: aruba-resource-v45
  namespace: default
spec:
  tenant: ARU-329997
  tags:
    - tag-4
    - tag-3
  location:
    value: ITBG-Bergamo
  projectReference:
    name: aruba-resource-v45
    namespace: default
