apiVersion: cloud.aruba.it/v1alpha1
kind: ArubaSubnet
metadata:
  name: aruba-resource-v45
  namespace: default
spec:
  tenant: ARU-329997
  tags:
    - tag-1
    - tag-2
  type: Advanced
  default: true
  network:
    address: 192.168.1.0/25
  dhcp:
    enabled: true
  vpcReference:
    name: aruba-resource-v45
    namespace: default
  projectReference:
    name: aruba-resource-v45
    namespace: default
