apiVersion: cloud.aruba.it/v1alpha1
kind: ArubaSecurityGroup
metadata:
  name: __NAME__
  namespace: default
spec:
  tenant: __TENANT__
  tags:
    - tag-1
    - tag-2
  location:
    value: ITBG-Bergamo
  default: false
  vpcReference:
    name: __NAME__
    namespace: default
  projectReference:
    name: __NAME__
    namespace: default
